{
    "openapi": "3.0.0",
    "info": {
        "title": "Sistema de classificação de anúncios",
        "description": "Esta API tem como objetivo classificar anúncios de diversos tipos",
        "version": "1.0.0"
    },
    "servers": [
        {
            "url": "http://localhost:3000"
        }
    ],
    "paths": {
        "/anuncios": {
            "get": {
                "summary": "Listar todos os anúncios criados",
                "description": "Esta rota será responsável por listar todos os anúncios criados.",
                "tags": ["Anuncios"],
                "responses": {
                    "200": {
                        "description": "uma lista de anúncios deve ser retornada",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#components/schemas/Anuncios"
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "summary": "Criar anúncios",
                "description": "Esta rota será responsável por criar anúncios.",
                "tags": ["Anuncios"],
                "security": [{ "bearerAuth": [] }],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#components/schemas/Anuncios"
                            },
                            "examples": {
                                "Anuncio": {
                                    "value": {
                                        "titulo": "Anuncio 1",
                                        "descricao": "Este é um teste.",
                                        "categoria": "Básico",
                                        "preco": 12.99,
                                        "anunciante": "Matheus",
                                        "contato": "1111-1111"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Anúncio criado.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#components/schemas/Anuncios"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/anuncios/cidades": {
            "get": {
                "summary": "Listar anúncios por cidade",
                "description": "Esta rota será responsável por listar anúncios que estão localizados em uma mesma cidade.",
                "tags": ["Anuncios"],
                "parameters": [
                    {
                        "name": "cidade",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "uma lista de anúncios da mesma cidade deve ser retornada",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#components/schemas/Anuncios"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/anuncios/categorias": {
            "get": {
                "summary": "Listar anúncios por categoria",
                "description": "Esta rota será responsável por listar anúncios da mesma categoria.",
                "tags": ["Anuncios"],
                "parameters": [
                    {
                        "name": "categoria",
                        "in": "query",
                        "required": false
                    }
                ],
                "responses": {
                    "200": {
                        "description": "uma lista de anúncios da mesma categoria deve ser retornada",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#components/schemas/Anuncios"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/anuncios/{id}": {
            "get": {
                "summary": "Mostrar anúncio por id",
                "description": "Esta rota será responsável por buscar um anúncio específico.",
                "tags": ["Anuncios"],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Um anúncio pelo id deve ser retornada",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#components/schemas/Anuncios"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Anúncio não encontrado."
                    }
                }
            },
            "put": {
                "summary": "Alterar anúncio",
                "description": "Esta rota será responsével por alterar os anúncios.",
                "tags": ["Anuncios"],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "security": [{ "bearerAuth": [] }],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#components/schemas/Anuncios"
                            },
                            "examples": {
                                "Anuncio": {
                                    "value": {
                                        "titulo": "Anuncio 1",
                                        "descricao": "Este é um teste.",
                                        "categoria": "Básico",
                                        "preco": 12.99,
                                        "anunciante": "Matheus",
                                        "cidade": "Brasília",
                                        "contato": "(61)1111-1111"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "204": {
                        "description": "Anúncio alterado."
                    },
                    "401": {
                        "description": "Esta resposta será dada caso o usuário não tenha autorização."
                    },
                    "404": {
                        "description": "Anúncio não encontrado."
                    }
                }
            },
            "delete": {
                "summary": "Remover anúncios",
                "description": "Esta rota será responsável por remover anúncios.",
                "tags": ["Anuncios"],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "security": [{ "bearerAuth": [] }],
                "responses": {
                    "200": {
                        "description": "Anúncio foi removido, não retorna nenhum conteúdo.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#components/schemas/Anuncios"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Não foi encontrado nenhum anúncio com esse id."
                    }
                }
            }
        },
        "/usuarios/registro": {
            "post": {
                "summary": "Registrar usuário",
                "description": "Esta rota será responsável por registrar novos usuários.",
                "tags": ["Usuários"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "$ref": "#components/schemas/Usuarios"
                            },
                            "examples": {
                                "Usuario": {
                                    "value": {
                                        "nome": "Matheus",
                                        "email": "matheus@gmail.com",
                                        "senha": "12345"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Usuário criado.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#components/schemas/Usuarios"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/usuarios/login":{
            "post": {
                "summary": "Login de usuário",
                "description": "Esta rota será responsável por realizar o login do usuário.",
                "tags": ["Usuários"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "$ref": "#components/schemas/Usuarios"
                            },
                            "examples": {
                                "Usuario": {
                                    "value": {
                                        "email": "matheus@gmail.com",
                                        "senha": "1G3t5$#8"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "summary": "Usuário logado",
                        "description": "Esta será a resposta em caso de sucesso.",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "Usuario": {
                                        "value": {
                                            "email": "matheus@gmail.com",
                                            "token": "eyJhbhciOiJIUz65NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzODgwMDdlODBiMT6DYTk2OWQwOWFjOSIsImlhdCI6MTY2OTg1NzQzMSwiZXhwIjoxNjY5OTQzODMxfQ.TRDUtsYeR7BJtVd79m-Mfw4KuvZXzjrsXk9lSGkokks"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "summary": "Usuário sem autorização",
                        "description": "Esta resposta será dada caso o usuário não tenha autorização."
                    },
                    "404": {
                        "summary": "Usuário não cadastrado",
                        "description": "Esta será a resposta caso usuário não esteja cadastrado."
                    }
                }
            }
        },
        "/usuarios/{id}": {
            "delete": {
                "summary": "Remover usuário",
                "description": "Esta rota será responsável por remover usuário.",
                "tags": ["Usuários"],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "security": [{ "bearerAuth": [] }],
                "responses": {
                    "204": {
                        "description": "Usuário removido."
                    },
                    "404": {
                        "description": "Usuário não foi encontrado."
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "Anuncios": {
                "type": "object",
                "properties": {
                    "_id": {
                        "type": "string",
                        "example": "6387efe4a9efa911d3a19770"
                    },
                    "titulo": {
                        "type": "string",
                        "example": "Apartamento"
                    },
                    "descricao": {
                        "type": "string",
                        "example": "2 quartos, sala e cozinha juntas, 1 banheiro"
                    },
                    "categoria": {
                        "type": "string",
                        "example": "Imóveis"
                    },
                    "preco": {
                        "type": "number",
                        "example": 100000.00
                    },
                    "anunciante": {
                        "type": "string",
                        "example": "Matheus"
                    },
                    "cidade": {
                        "type": "string",
                        "example": "Brasília"
                    },
                    "contato": {
                        "type": "string",
                        "example": "(61)1212-1212"
                    }
                }
            },
            "Usuarios": {
                "type": "object",
                "properties": {
                    "_id": {
                        "type": "string",
                        "example": "6388007e80b129a969d09ac9"
                    },
                    "nome": {
                        "type": "string",
                        "example": "Matheus"
                    },
                    "email": {
                        "type": "string",
                        "example": "matheus@gmail.com"
                    },
                    "senha": {
                        "type": "string",
                        "example": "G2t4#578"
                    }
                }
            }
        },
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            }
        }
    }
}